version: '2'
#Some colons should follow a space, otherwise will get errors....
services:
    db:
        image: mysql:5.7
        # build: ./server_config
        volumes:
          - ./mysql_data:/var/lib/mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: wordpress
          MYSQL_USER: you
          MYSQL_PASSWORD: yourpassword  
        networks:
          - back-network
          
         
   
    php:
         # image: php:7-fpm
         # volumes:
          # - ./:/code
        networks:
            - back-network
        depends_on:
            - db
            - php_config_db
        image: wordpress:latest
        volumes:
          - ./:/var/www/html #Same as WP_FOLDER
        ports:
         - "80:80"
        restart: always
        environment:
          WORDPRESS_DB_HOST: db:3306
          WORDPRESS_DB_USER: you
          WORDPRESS_DB_PASSWORD: yourpassword
          
    php_config_db:
        build: 
            context: ./server_config
            args:
                #####################You must change the url here when used in the remote server###############################
                WP_HOME: http://localhost
                #If you use port 80, please leave the port empty. You can specify other ports here. The port should be the same as the external port used in php.
                WP_SITEURL: http://localhost
                #####################Used in production########################################################################
                WP_FOLDER: ./
        networks:
            - back-network
        command: /usr/local/bin/docker-entrypoint.sh
        depends_on:
            - db
        #restart: always
        
 
        
networks:
    # front-network:
        # external:
            # name: back-network
    back-network:
        driver: bridge